crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from leads.views import HomepageView

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("lead/", include("leads.urls", namespace="leads")),
    path("agent/", include("agents.urls", namespace="agents")),
    path("category/", include("categorys.urls", namespace="categorys")),
]

# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentview,
    LeadCategoryUpdateView,
)

app_name = "leads"
urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("create/", LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/assign/", AssignAgentview.as_view(), name="assign_agent"),
    path(
        "category/<int:pk>/lead/update/",
        LeadCategoryUpdateView.as_view(),
        name="lead_category_update",
    ),
]

leads/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    # each user can have only one user profile
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("agents:agent_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)  # Contacted, Converted, Unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.PositiveIntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, related_name="leads"
    )
    description = models.TextField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=10)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("leads:lead_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


def post_user_created_signal(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from .models import Lead, Agent


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "email",
            "phone_number",
            "agent",
            "description",
        )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super().__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)

leads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views import generic

from agents.mixins import OrganisorAndLoginRequiredMixin

from .forms import LeadModelForm, AssignAgentForm, LeadCategoryUpdateForm
from .models import Lead


class HomepageView(generic.TemplateView):
    template_name = "homepage.html"


class LeadListView(LoginRequiredMixin, generic.ListView):
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user

        # Return leads associated to the organisation.
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile, agent__isnull=False
            )
        else:  # is_agent
            # Return leads associated to the agent organisation.
            queryset = Lead.objects.filter(
                organisation=user.agent.organisation, agent__isnull=False
            )
            # Return leads only assigned to the logged in agent.
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile,
                agent__isnull=True,
            )
        context.update(
            {
                "unassigned_leads": queryset,
            }
        )
        return context


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user

        # Return leads associated to the organisation.
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:  # is_agent
            # Return leads associated to the agent organisation.
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            # Return leads only assigned to the logged in agent.
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    form_class = LeadModelForm
    template_name = "leads/lead_create.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                "request": self.request,
            }
        )
        return kwargs

    # Sends mails everytime a new lead is created
    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="A lead has been created",
            message="Go to the site to to view lead",
            from_email="admin@test.com",
            recipient_list=["test@test.com"],
        )
        return super(LeadCreateView, self).form_valid(form)


class LeadUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    form_class = LeadModelForm
    context_object_name = "lead"
    template_name = "leads/lead_update.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                "request": self.request,
            }
        )
        return kwargs

    def get_queryset(self):
        user = self.request.user
        # Return leads associated to the organisation.
        return Lead.objects.filter(organisation=user.userprofile)

    def form_valid(self, form):
        form.save()
        return super(LeadUpdateView, self).form_valid(form)


class LeadDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    model = Lead
    context_object_name = "lead"
    success_url = reverse_lazy("leads:lead_list")
    template_name = "leads/lead_delete.html"

    def get_queryset(self):
        user = self.request.user
        # Return leads associated to the organisation.
        return Lead.objects.filter(organisation=user.userprofile)


class AssignAgentview(OrganisorAndLoginRequiredMixin, generic.FormView):
    """Assign agents to unassigned leads."""

    form_class = AssignAgentForm
    success_url = reverse_lazy("leads:lead_list")
    template_name = "leads/assign_agent.html"

    def get_form_kwargs(self, **kwargs) -> dict[str]:
        kwargs = super(AssignAgentview, self).get_form_kwargs(**kwargs)
        kwargs.update(
            {
                "request": self.request,
            }
        )
        return kwargs

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentview, self).form_valid(form)


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    form_class = LeadCategoryUpdateForm
    template_name = "leads/lead_category_update.html"

    def get_queryset(self):
        user = self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset

    # def get_success_url(self):
    # return reverse_lazy("leads:lead_detail", kwargs={"pk": self.get_object().id})

leads/templates/leads/assign_agent.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mt-8 mx-auto">
    <div class="py-5 border-b border-gray-200">
        <h1 class="text-4xl text-gray-800">Assign an agent</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Create
            </button>
        </form>
    </div>
</div>
{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Category
                    </a>
                    <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Update
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mt-8 mx-auto">
    <div class="py-5 border-b border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new lead</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Create
            </button>
        </form>
    </div>
</div>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="max-w-lg mx-auto">
    <div class="py-5 border-gray-200">
        <form class="mt-5" action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ lead }}"?</p>
            <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">
                Delete
            </button>
        </form>
        <div class="py-5">
            <a class="hover:text-blue-500 underline" href="{% url 'leads:lead_detail' lead.pk %}">Cancel</a>
        </div>
    </div>
</div>
    
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'leads:lead_category_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Category
                    </a>
                    <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{ lead.age }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{ lead.email }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Phone Number</span>
                    <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}

{% block content %}

<!-- Assigned Leads -->
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>
      {% if request.user.is_organisor %}
      <div>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'leads:lead_create' %}"
          >Create a new lead
        </a>
      </div>
      {% endif %}
    </div>

    {% if leads %}
    <div class="flex flex-col w-full">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div
            class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
          >
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    First Name
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Last Name
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Age
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Email
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Cell Phone Number
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Category
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for lead in leads %}
                <tr class="bg-white">
                  <td
                    class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                  >
                    <a
                      class="hover:text-indigo-500"
                      href="{% url 'leads:lead_detail' lead.pk %}"
                      >{{ lead.first_name }}</a
                    >
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ lead.last_name }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ lead.age }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ lead.email }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ lead.phone_number }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    {% if lead.category %}
                    <span
                      class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"
                    >
                      {{ lead.category.name }}
                    </span>
                    {% else %}
                    <span
                      class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800"
                    >
                      Unassigned
                    </span>
                    {% endif %}
                  </td>
                  <td
                    class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                  >
                    <a
                      href="{% url 'leads:lead_update' lead.pk %}"
                      class="text-indigo-600 hover:text-indigo-900"
                    >
                      Edit
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <p>There are currently no leads</p>
    {% endif %}
  </div>

  <!-- Unassigned Leads -->
  {% if unassigned_leads.exists %}
  <div class="container px-5 py-6 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
      </div>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in unassigned_leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ lead }}
            </h2>
            <p class="leading-relaxed text-base">{{ lead.description }}</p>
            <a
              href="{% url 'leads:assign_agent' lead.pk %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
            >
              Assign agent
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
</section>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'leads:lead_category_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Category
                    </a>
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Update
                    </button>
                </form>
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{% url 'leads:lead_delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}