agents/urls.py
from django.urls import path
from .views import (
    AgentListView,
    AgentCreateView,
    AgentDetailView,
    AgentUpdateView,
    AgentDeleteView,
)

app_name = "agents"
urlpatterns = [
    path("", AgentListView.as_view(), name="agent_list"),
    path("create/", AgentCreateView.as_view(), name="agent_create"),
    path("<int:pk>/", AgentDetailView.as_view(), name="agent_detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent_update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent_delete"),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from leads.views import HomepageView

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("lead/", include("leads.urls", namespace="leads")),
    path("agent/", include("agents.urls", namespace="agents")),
    path("category/", include("categorys.urls", namespace="categorys")),
]

# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
        )

agents/views.py
import random

from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views import generic

from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin


class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    context_object_name = "agents"
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        """Return agents associated with the orgranisor's organisation."""
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    """Create agent/user with is_agent=True."""

    form_class = AgentModelForm
    success_url = reverse_lazy("agents:agent_list")
    template_name = "agents/agent_create.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(1, 100_000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile,
        )
        send_mail(
            subject="You're invited to be an agent",
            message="You were added as an agent. Please login!",
            from_email="admin@test.com",
            recipient_list=[user.email],
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    context_object_name = "agent"
    template_name = "agents/agent_detail.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    context_object_name = "agent"
    form_class = AgentModelForm
    success_url = reverse_lazy("agents:agent_list")
    template_name = "agents/agent_update.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs["instance"] = kwargs["instance"].user
        return kwargs


class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    context_object_name = "agent"
    success_url = reverse_lazy("agents:agent_list")
    template_name = "agents/agent_delete.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mt-8 mx-auto">
    <div class="py-5 border-b border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new agent</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Create
            </button>
        </form>
    </div>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mt-8 mx-auto">
    <div class="py-5 border-gray-200">
        <h1 class="text-3xl text-gray-800">Are you sure you want to delete agent "{{ agent }}"?</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Delete
            </button>
        </form>
        <div class="py-5">
            <a class="hover:text-blue-500 underline" href="{% url 'agents:agent_detail' agent.pk %}">Cancel</a>
        </div>
    </div>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %}


{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'agents:agent_update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{ agent.age }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Organisation</span>
                    <span class="ml-auto text-gray-900">{{ agent.organisation }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Cell phone</span>
                    <span class="ml-auto text-gray-900">+97732323</span>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Agents</h1>
      </div>
      <div>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'agents:agent_create' %}"
          >Create a new agent
        </a>
      </div>
    </div>

    {% if agents %}
    <div class="flex flex-col w-full">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div
            class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
          >
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Full Name
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Email
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for agent in agents %}
                <tr class="bg-white">
                  <td
                    class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                  >
                    <a
                      href="{% url 'agents:agent_detail' agent.pk %}"
                      class="hover:text-indigo-500"
                    >
                      {{ agent.user.first_name }} {{ agent.user.last_name }}
                    </a>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ agent.user.email }}
                  </td>
                  <td
                    class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                  >
                    <a
                      href="{% url 'agents:agent_update' agent.pk %}"
                      class="text-indigo-600 hover:text-indigo-900"
                    >
                      Edit
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <p>There are currently no agents</p>
    {% endif %}
  </div>
</section>

{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:agent_detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Update
                    </button>
                </form>
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{% url 'agents:agent_delete' agent.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}