accounts/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    SignUpView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "accounts"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

agents/urls.py
from django.urls import path
from .views import (
    AgentListView,
    AgentCreateView,
    AgentDetailView,
    AgentUpdateView,
    AgentDeleteView,
)

app_name = "agents"
urlpatterns = [
    path("", AgentListView.as_view(), name="agent_list"),
    path("create/", AgentCreateView.as_view(), name="agent_create"),
    path("<int:pk>/", AgentDetailView.as_view(), name="agent_detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent_update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent_delete"),
]

categorys/urls.py
from django.urls import path
from .views import (
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)


app_name = "categorys"
urlpatterns = [
    path("", CategoryListView.as_view(), name="category_list"),
    path("create/", CategoryCreateView.as_view(), name="category_create"),
    path("<int:pk>/", CategoryDetailView.as_view(), name="category_detail"),
    path("<int:pk>/update/", CategoryUpdateView.as_view(), name="category_update"),
    path("<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from leads.views import HomepageView

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("lead/", include("leads.urls", namespace="leads")),
    path("agent/", include("agents.urls", namespace="agents")),
    path("category/", include("categorys.urls", namespace="categorys")),
]

# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentview,
    LeadCategoryUpdateView,
)

app_name = "leads"
urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("create/", LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/assign/", AssignAgentview.as_view(), name="assign_agent"),
    path(
        "category/<int:pk>/lead/update/",
        LeadCategoryUpdateView.as_view(),
        name="lead_category_update",
    ),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="max-w-7xl mx-auto">
        {% include 'messages.html' %}
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/dashboard.svg' %}">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                CRM built with Django
            </h1>
            <p class="mb-8 leading-relaxed">
                This CRM helps you manage your leads.
            </p>
            {% if not request.user.is_authenticated %}
            <div class="flex justify-center">
                <a href="{% url 'accounts:login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                    Login to get started
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 border-l-4
        {% if message.tags == 'success' %}
        bg-green-50 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
            <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-700
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a href="{% url 'homepage' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <img src="{% static 'images/logo.svg' %}" alt="logo">
            <span class="ml-3 text-xl">CRM</span>
        </a>
        <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            {% if request.user.is_authenticated %}
                {% if request.user.is_organisor %}
                <a href="{% url 'agents:agent_list' %}" class="mr-5 hover:text-gray-900">Agents</a>
                {% endif %}
            <a href="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-900">Leads</a>
            <a href="{% url 'categorys:category_list' %}" class="mr-5 hover:text-gray-900">Category</a>
            {% else %}
            <a href="{% url 'accounts:signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
            {% endif %}
        </nav>
        {% if user.is_authenticated %}
        Logged in as: {{ user.username }}
        <a href="{% url 'accounts:logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Logout
        </a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Login
        </a>
        {% endif %}
    </div>
</header>