categorys/urls.py
from django.urls import path
from .views import (
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)


app_name = "categorys"
urlpatterns = [
    path("", CategoryListView.as_view(), name="category_list"),
    path("create/", CategoryCreateView.as_view(), name="category_create"),
    path("<int:pk>/", CategoryDetailView.as_view(), name="category_detail"),
    path("<int:pk>/update/", CategoryUpdateView.as_view(), name="category_update"),
    path("<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from leads.views import HomepageView

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("lead/", include("leads.urls", namespace="leads")),
    path("agent/", include("agents.urls", namespace="agents")),
    path("category/", include("categorys.urls", namespace="categorys")),
]

# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentview,
    LeadCategoryUpdateView,
)

app_name = "leads"
urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("create/", LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/assign/", AssignAgentview.as_view(), name="assign_agent"),
    path(
        "category/<int:pk>/lead/update/",
        LeadCategoryUpdateView.as_view(),
        name="lead_category_update",
    ),
]

categorys/models.py
from django.db import models

# Create your models here.

categorys/forms.py
from django import forms

from leads.models import Category


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("name",)

categorys/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from agents.mixins import OrganisorAndLoginRequiredMixin
from leads.models import Lead, Category

from .forms import CategoryModelForm


class CategoryListView(LoginRequiredMixin, generic.ListView):
    context_object_name = "categories"
    template_name = "categorys/category_list.html"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
        context.update(
            {
                "unassigned_lead_count": queryset.filter(category__isnull=True).count(),
            }
        )
        return context

    def get_queryset(self):
        user = self.request.user

        # Return leads associated to the organisation.
        if user.is_organisor:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:  # is_agent
            # Return leads associated to the agent organisation.
            queryset = Category.objects.filter(organisation=user.agent.organisation)
        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    context_object_name = "category"
    template_name = "categorys/category_detail.html"

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        # leads = related_name attribute from Lead model
        leads = self.get_object().leads.all()

        context.update(
            {
                "leads": leads,
            }
        )
        return context

    def get_queryset(self):
        user = self.request.user

        if user.is_organisor:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)
        return queryset


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = CategoryModelForm
    success_url = reverse_lazy("categorys:category_list")
    template_name = "categorys/category_create.html"

    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)


class CategoryUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    form_class = CategoryModelForm
    success_url = reverse_lazy("categorys:category_list")
    template_name = "categorys/category_update.html"

    def get_queryset(self):
        user = self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
        return queryset


class CategoryDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    success_url = reverse_lazy("categorys:category_list")
    template_name = "categorys/category_delete.html"

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)
        return queryset

categorys/templates/categorys/category_create.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new category</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Create
        </button>
    </form>
</div>
{% endblock content %}

categorys/templates/categorys/category_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-t border-gray-200">
        <h2 class="text-4xl text-gray-800">Are you sure you want to delete category "<strong>{{ object.name }}</strong>"?</h2>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Delete
        </button>
    </form>
</div>
{% endblock content %}

categorys/templates/categorys/category_detail.html
{% extends 'base.html' %}


{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
            <div>
                <a class="hover:text-blue-500" href="{% url 'categorys:category_update' category.pk %}">Update</a> |
                <a class="hover:text-blue-500" href="{% url 'categorys:category_delete' category.pk %}">Delete</a>
            </div>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            First Name
                        </th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Last Name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for lead in category.leads.all %}
                    <tr>
                        <td class="px-4 py-3">
                            <a class="hover:text-blue-500" href="{% url 'leads:lead_detail' lead.pk %}">{{ lead.first_name }}</a>
                        </td>
                        <td class="px-4 py-3">{{ lead.last_name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </section>

{% endblock content %}

categorys/templates/categorys/category_list.html
{% extends 'base.html' %}


{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories segment the leads</p>
            <div>
                <a class="hover:text-blue-500" href="{% url 'categorys:category_create' %}">Create a category</a>
            </div>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="px-4 py-3">Unassigned</td>
                        <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
                    </tr>
                    {% for category in categories %}
                    <tr>
                        <td class="px-4 py-3">
                            <a class="hover:text-blue-500" href="{% url 'categorys:category_detail' category.pk %}">{{ category.name }}</a>
                        </td>
                        <td class="px-4 py-3">count</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </section>

{% endblock content %}

categorys/templates/categorys/category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update {{ object.name }}</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Update
        </button>
    </form>
</div>

{% endblock content %}